
server:
  port: 8080
spring:
  application:
    name: security
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useSSL=false
    username: root
    password: 123456
  redis:
    port: 6379
    password: ldx666
    host: 139.9.70.25
    database: 13
